# Generated by Django 4.2.7 on 2024-01-03 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_community_members'),
        ('post', '0003_post_in_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='in_community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community'),
        ),
    ]
