# Generated by Django 4.2.9 on 2024-01-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_message_datetime_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datetime_sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
