# Generated by Django 4.2.9 on 2024-01-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_community_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name_plural': 'Communities'},
        ),
    ]
